<?php

namespace App\CoreBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    
    /**
     * Returns all categories ordered by title ascendant.
     *
     * @return \App\CoreBundle\Entity\category
     */
    public function getCategories()
    {
        return $this->findBy([], [ 'title' => 'ASC' ]);
    }
}
