<?php

namespace App\CoreBundle\Repository;

use App\CoreBundle\Repository\AbstractRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends AbstractRepository
{
    
    /**
     * Returns all categories ordered by title ascendant.
     *
     * @return \App\CoreBundle\Entity\category
     */
    public function getCategories()
    {
        return $this->findBy([], [ 'title' => 'ASC' ]);
    }
    
        /**
     * @param string $term
     * @param string $order
     *
     * @return \Traversable
     */
    public function search($term, $order = 'asc', $limit = 20, $offset = 0)
    {
        $qb = $this
            ->createQueryBuilder('c')
            ->select('c')
            ->orderBy('c.title', $order)
        ;

        if ($term) {
            $qb
                ->where('c.title LIKE ?1')
                ->setParameter(1, '%' . $term . '%')
            ;
        }

        return $this->paginate($qb, $limit, $offset);
    }
}
